import numpy as np
# a = np.arange(100).reshape(20,5)
# # print("a", a)
# # print("a.ndim", a.ndim)
# # print("a.dtype.name", a.dtype.name)
# # print("a.itemsize", a.itemsize)
# # print("a.shape", a.shape)
# # print("a.size", a.size)
# # print("type(a)", type(a))
# # print("a.ndim", a.ndim)
# # print("a.data", a.data)
#
# print("a.ndim", a.ndim)
# print("a.shape", a.shape)
# b = np.array([(a), (a)])
# print("b.ndim", b.ndim)
# print("b.shape", b.shape)
# # print(b)
# c = np.array([(1,2), (3,4)])
# d = np.array([(c), [(5,6), (7,9)]])
# print("c.ndim", c.ndim)
# print("c.shape", c.shape)
# print("d.ndim", d.ndim)
# print("d.shape", d.shape)
# e = np.array([d, [[(1,2), (1,2)], [(1,2), (1,2)]]])
# print("e.ndim", e.ndim)
# print("e.shape", e.shape)
# print(e)
print(np.arange(10, 30, 5))
